CREATE TABLE IF NOT EXISTS tokens (
    id CHAR(36) DEFAULT (UUID()) PRIMARY KEY NOT NULL,
    user_id CHAR(36) NOT NULL,
    token_hash CHAR(64) UNIQUE NOT NULL,
    expired_at DATETIME DEFAULT (DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 24 HOUR)),
    FOREIGN KEY (user_id) REFERENCES users(id)
);