name: api_db

services:
  db:
    image: mysql:8.0.45
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - api_db_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
  cache:
    image: redis:8.6.2
    container_name: cache
    environment:
      - REDIS_ROOT_PASSWORD=${REDIS_ROOT_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
    ports:
      - 6379:6379
    volumes:
      - api_cache_volume:/data
      - ./cache/redis_init.sh:/usr/local/bin/init-redis.sh
    command: ["sh", "/usr/local/bin/init-redis.sh"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_ROOT_PASSWORD}","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  flyway:
    depends_on:
      db:
        condition: service_healthy
    image: flyway/flyway:12.3.0
    command: migrate
    environment:
      - FLYWAY_URL=jdbc:mysql://db:3306/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
      - FLYWAY_USER=${DB_USER}
      - FLYWAY_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./DB/migrations:/flyway/sql

volumes:
  api_db_volume:
  api_cache_volume: